version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/mainpage"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10