services:
  subconv:
    build:
      context: .
      dockerfile: Dockerfile
    image: wouisb/subconv:latest
    container_name: subconv
    restart: unless-stopped
    ports:
      - "58288:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./template:/app/template
