name: Build and Push Container Image

on:
  workflow_call:
    inputs:
      tags:
        description: 'Tag to use for the image'
        type: string
        required: true
        default: 'dev'

permissions:
  contents: read
  packages: write

env:
  IMAGE_REPOSITORY: wouisb/subconv

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tag.outputs.TAG_NAME }}
    steps:
      - id: tag
        run: |
          # get tag from input (comma separated) and image_repository
          new_tag=""
          for tag in $(echo ${{ inputs.tags }} | tr "," "\n"); do
            new_tag="$new_tag,${{ env.IMAGE_REPOSITORY }}:$tag"
          done
          # outupt
          echo "TAG_NAME=$new_tag" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Cache Nuitka cache
      uses: actions/cache@v4
      with:
        path: nuitka-cache
        key: nuitka-cache

    - name: Inject Nuitka cache into Docker
      uses: reproducible-containers/buildkit-cache-dance@v2.1.4
      with:
        cache-source: nuitka-cache
        cache-target: /root/.cache/Nuitka

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ needs.setup.outputs.tags }}
        platforms: |
          linux/amd64
          linux/arm64
